spring:
  application:
    name: desafio-seplag-backend

  # Configura��o do Banco de Dados
  datasource:
    # Se estiver rodando no IntelliJ/Windows, usa localhost.
    # Se estiver rodando dentro do Docker, usar� o nome do container (configuraremos via variavel de ambiente depois)
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    # Tenta conectar no host (Docker) ou localhost (IDE) dinamicamente
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/desafio_db
    driver-class-name: org.postgresql.Driver

  # Configura��o do JPA (Hibernate)
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  # Configura��o do Flyway (Migra��es)
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Configura��o do MinIO (Customizada)
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: capas-albuns
  public-url: ${MINIO_PUBLIC_URL:http://localhost:9000}

# Configura��o do Actuator (Health Checks - Exig�ncia S�nior)
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

api:
  security:
    token:
      secret: Hornet@2025